### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by ghost** [youngwolf-project/ascs#1]
我记得是多年前关注过这个项目，在CSDN博客读过项目相关的文章；几年之后看到项目一直在更新维护，非常感谢你的工作。另外就是ascs是否与st_asio_wrapper保持一致，两者的性能相差多少？

**Comment by youngwolf-project** [comment]
谢谢你的关注。
ascs在运行效率上要优于st库，在编译速度上更是大大的优于st库，即便是为st库开启c++0x功能也是如此，这也是boost的臃肿所在。
为此，我推荐，只要c++0x可用，就要用ascs，即便你用了boost也可以同时用ascs，只不过用ascs的话你要自己去下载asio (http://think-async.com/)，然后定义ASIO_STANDALONE宏（参看我的makefile文件）。
注意，boost.asio也可以独立使用（定义BOOST_ASIO_STANDALONE宏），ascs必须用non-boost的版本（参看http://think-async.com/）。
